<?php

namespace ContainerGJVdbt3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPortefeuilleControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PortefeuilleController' shared autowired service.
     *
     * @return \App\Controller\PortefeuilleController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PortefeuilleController.php';

        $container->services['App\\Controller\\PortefeuilleController'] = $instance = new \App\Controller\PortefeuilleController(($container->privates['App\\Service\\PortefeuilleService'] ?? $container->load('getPortefeuilleServiceService')));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\PortefeuilleController', $container));

        return $instance;
    }
}
