<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'clients_create' => [[], ['_controller' => 'App\\Controller\\ClientController::create'], [], [['text', '/clients/create']], [], [], []],
    'clients_read' => [['clientId'], ['_controller' => 'App\\Controller\\ClientController::read'], [], [['variable', '/', '[^/]++', 'clientId', true], ['text', '/clients']], [], [], []],
    'clients_update' => [['clientId'], ['_controller' => 'App\\Controller\\ClientController::update'], [], [['variable', '/', '[^/]++', 'clientId', true], ['text', '/clients/update']], [], [], []],
    'clients_delete' => [['clientId'], ['_controller' => 'App\\Controller\\ClientController::delete'], [], [['variable', '/', '[^/]++', 'clientId', true], ['text', '/clients/delete']], [], [], []],
    'clients_seconnecter' => [[], ['_controller' => 'App\\Controller\\ClientController::seConnecter'], [], [['text', '/seconnecter']], [], [], []],
    'crediter_portefeuille' => [['portefeuilleId'], ['_controller' => 'App\\Controller\\PortefeuilleController::crediter'], [], [['variable', '/', '[^/]++', 'portefeuilleId', true], ['text', '/portefeuille/crediter']], [], [], []],
    'debiter_portefeuille' => [['portefeuilleId'], ['_controller' => 'App\\Controller\\PortefeuilleController::debiter'], [], [['variable', '/', '[^/]++', 'portefeuilleId', true], ['text', '/portefeuille/debiter']], [], [], []],
    'creer_portefeuille' => [['clientId'], ['_controller' => 'App\\Controller\\PortefeuilleController::creer'], [], [['variable', '/', '[^/]++', 'clientId', true], ['text', '/portefeuille/creer']], [], [], []],
    'afficher_portefeuille' => [['portefeuilleId'], ['_controller' => 'App\\Controller\\PortefeuilleController::getPortefeuille'], [], [['variable', '/', '[^/]++', 'portefeuilleId', true], ['text', '/portefeuille/afficher']], [], [], []],
    'chambre_standard_create' => [[], ['_controller' => 'App\\Controller\\ChambreController::creerChambreStandard'], [], [['text', '/chambres/standard']], [], [], []],
    'chambre_superieur_create' => [[], ['_controller' => 'App\\Controller\\ChambreController::creerChambreSuperieur'], [], [['text', '/chambres/superieur']], [], [], []],
    'chambre_suite_create' => [[], ['_controller' => 'App\\Controller\\ChambreController::creerSuite'], [], [['text', '/chambres/suite']], [], [], []],
    'chambre_list' => [[], ['_controller' => 'App\\Controller\\ChambreController::listerChambres'], [], [['text', '/chambres']], [], [], []],
    'chambre_delete' => [['chambre'], ['_controller' => 'App\\Controller\\ChambreController::deleteChambre'], [], [['variable', '/', '[^/]++', 'chambre', true], ['text', '/chambres/supprimer']], [], [], []],
    'reservation_creer' => [[], ['_controller' => 'App\\Controller\\ReservationController::creerReservation'], [], [['text', '/reservation/creer']], [], [], []],
];
