<?php

namespace Container92hFasJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChambreControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ChambreController' shared autowired service.
     *
     * @return \App\Controller\ChambreController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ChambreController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ChambreServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ChambreService.php';

        $container->services['App\\Controller\\ChambreController'] = $instance = new \App\Controller\ChambreController(new \App\Service\ChambreService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'))));

        $instance->setContainer(($container->privates['.service_locator.jUv.zyj'] ?? $container->load('get_ServiceLocator_JUv_ZyjService'))->withContext('App\\Controller\\ChambreController', $container));

        return $instance;
    }
}
